### ISSUE TITLE
ImportError: No module named run_calc_hungarian_alignment_score

### ISSUE THREAD

**Issue by ghost** [Cisco-Talos/fnc-1#5]
When I ran xgb_train_cvBodyId.py, this error was happened.

```
Traceback (most recent call last):
  File "xgb_train_cvBodyId.py", line 16, in <module>
    from AlignmentFeatureGenerator import *
  File "/root/work/fnc-1/tree_model/AlignmentFeatureGenerator.py", line 11, in <                                                                                                                               module>
    from run_calc_hungarian_alignment_score import *
ImportError: No module named run_calc_hungarian_alignment_score
```

Because there is no module "run_calc_hungarian_alignment_score". 
Please check that we can run them completely if we follow the README.md.

**Comment by yuxip** [comment]
Remove the line that imports AlignmentFeatureGenerator

**Comment by ghost** [comment]
I replaced this:

`from run_calc_hungarian_alignment_score import *
`

to:

`from score import *`

and it worked. Thanks.
