### ISSUE TITLE
IOError: File test_stances_unlabeled_processed.csv does not exist

### ISSUE THREAD

**Issue by ghost** [Cisco-Talos/fnc-1#6]
When I ran "xgb_train_cvBodyId.py", it happened.

```
Traceback (most recent call last):
  File "xgb_train_cvBodyId.py", line 398, in <module>
    train()
  File "xgb_train_cvBodyId.py", line 182, in train
    stances = pd.read_csv("test_stances_unlabeled_processed.csv") # same row ord                                                                                                                               er as predicted
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 678,                                                                                                                                in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 440,                                                                                                                                in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 787,                                                                                                                                in __init__
    self._make_engine(self.engine)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 1014,                                                                                                                                in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/lib/python2.7/site-packages/pandas/io/parsers.py", line 1708,                                                                                                                                in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.                                                                                                                               __cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader.                                                                                                                               _setup_parser_source
IOError: File test_stances_unlabeled_processed.csv does not exist
```

There is no file called  "test_stances_unlabeled_processed.csv".
What's the file, and how to generate it?

**Comment by yuxip** [comment]
use test_stances_unlabeled.csv

**Comment by ghost** [comment]
Thanks, it works.
